import React, { useEffect, useState } from 'react';
import { AlertCircle, CheckCircle2, FileText, ShieldCheck } from 'lucide-react';
import { Link, useLocation, useParams } from 'react-router-dom';
import { getComplaintById, subscribeComplaints } from '../services/complaintService';
import { ReportActions } from '../components/report/ReportActions';

export const ComplaintReportPage = ({ isOfficer = false }) => {
  const { complaintId } = useParams();
  const { search } = useLocation();
  const [complaint, setComplaint] = useState(() => getComplaintById(complaintId));
  const backPath = isOfficer ? `/complaints/${complaintId}` : '/customer/complaints';

  useEffect(() => {
    setComplaint(getComplaintById(complaintId));
    return subscribeComplaints(() => setComplaint(getComplaintById(complaintId)));
  }, [complaintId]);

  useEffect(() => {
    if (!new URLSearchParams(search).has('download')) return undefined;
    const timer = window.setTimeout(() => document.getElementById('complaint-report-download')?.click(), 0);
    return () => window.clearTimeout(timer);
  }, [search]);

  if (!complaint || !complaint.reportAvailable) {
    return (
      <div className="max-w-3xl mx-auto py-16 text-center space-y-4">
        <div className="mx-auto flex h-14 w-14 items-center justify-center rounded-2xl bg-amber-50 text-amber-600 border border-amber-200"><AlertCircle className="h-7 w-7" /></div>
        <h1 className="text-xl font-black text-slate-900">Complaint Report Unavailable</h1>
        <p className="text-sm text-slate-500">Report has not been generated by the reviewing officer yet.</p>
        <Link to={backPath} className="inline-flex rounded-xl bg-slate-900 px-4 py-2.5 text-xs font-bold text-white">Back to Complaint</Link>
      </div>
    );
  }

  const reportId = complaint.generatedReportId;
  const generatedAt = complaint.generatedAt ? new Date(complaint.generatedAt).toLocaleString() : '—';
  const status = (complaint.status || 'SUBMITTED').replaceAll('_', ' ');

  return (
    <div className="space-y-6 pb-12">
      <ReportActions
        inspectionId={complaint.inspectionId}
        reportId={reportId}
        backPath={backPath}
        backLabel={isOfficer ? 'Back to Complaint' : 'Back to Complaints'}
        showGenerateAgain={false}
        downloadButtonId="complaint-report-download"
      />
      <article id="report-print-target" className="mx-auto max-w-4xl rounded-2xl border border-slate-300 bg-white p-8 sm:p-12 text-slate-900 shadow-md">
        <header className="mb-8 flex flex-col justify-between gap-4 border-b-2 border-slate-900 pb-6 sm:flex-row sm:items-start">
          <div className="flex items-center gap-3"><div className="flex h-12 w-12 items-center justify-center rounded-xl bg-[#0c1e33] font-black text-xl text-cyan-400">LS</div><div><h1 className="text-2xl font-black tracking-tight text-[#0c1e33]">LABEL SETU</h1><p className="text-xs font-semibold text-slate-600">Official Complaint Report</p></div></div>
          <div className="space-y-1 rounded-lg border border-slate-200 bg-slate-50 p-3 text-xs sm:border-0 sm:bg-transparent sm:p-0 sm:text-right"><p>Report ID: <strong className="font-mono">{reportId}</strong></p><p>Complaint ID: <strong className="font-mono">{complaint.complaintId || complaint.id}</strong></p><p>Inspection ID: <strong className="font-mono">{complaint.inspectionId || '—'}</strong></p><p>Generated: <strong>{generatedAt}</strong></p></div>
        </header>
        <div className="space-y-6 text-xs">
          <section className="rounded-xl border border-slate-200 bg-slate-50 p-4"><div className="mb-3 flex items-center gap-2 border-b border-slate-200 pb-2"><FileText className="h-4 w-4 text-cyan-700" /><h2 className="font-bold uppercase tracking-wide">Complaint Summary</h2></div><div className="grid grid-cols-1 gap-4 sm:grid-cols-2"><ReportField label="Product" value={complaint.productName || complaint.product} /><ReportField label="Complaint Category" value={complaint.category || complaint.complaintType} /><ReportField label="Date Filed" value={complaint.submittedAt ? new Date(complaint.submittedAt).toLocaleString() : complaint.date} /><ReportField label="Complaint Status" value={status} /></div><div className="mt-4"><span className="text-[10px] font-bold uppercase tracking-wider text-slate-500">Customer Description</span><p className="mt-1.5 leading-relaxed text-slate-800">{complaint.description || 'No description submitted.'}</p></div></section>
          <section className="rounded-xl border border-cyan-200 bg-cyan-50/50 p-4"><div className="mb-3 flex items-center gap-2 border-b border-cyan-100 pb-2"><ShieldCheck className="h-4 w-4 text-cyan-700" /><h2 className="font-bold uppercase tracking-wide">Officer Verification</h2></div><div className="grid grid-cols-1 gap-4 sm:grid-cols-2"><ReportField label="Generated By" value={complaint.generatedBy?.name || 'Authorized Officer'} /><ReportField label="Officer Decision" value={complaint.officerDecision || 'Pending final decision'} /></div>{complaint.officerRemarks && <p className="mt-4 leading-relaxed text-slate-700"><strong>Officer Remarks:</strong> {complaint.officerRemarks}</p>}</section>
          {complaint.aiAnalysis && <section className="rounded-xl border border-purple-200 bg-purple-50/50 p-4"><h2 className="font-bold uppercase tracking-wide text-purple-900">AI Preliminary Analysis</h2><p className="mt-2 leading-relaxed text-slate-800">{complaint.aiAnalysis.issue || 'Analysis available for officer review.'}</p><p className="mt-1 font-semibold text-purple-700">Confidence: {complaint.aiAnalysis.confidence || 0}%</p></section>}
          <div className="flex items-center gap-2 rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-emerald-800"><CheckCircle2 className="h-4 w-4" /><span className="font-semibold">This report is an officer-generated record linked to the complaint and its inspection.</span></div>
        </div>
      </article>
    </div>
  );
};

const ReportField = ({ label, value }) => <div><span className="block text-[10px] font-bold uppercase tracking-wider text-slate-500">{label}</span><span className="mt-1 block font-semibold text-slate-900">{value || '—'}</span></div>;
